spring:
  application:
    name: gateway
  cloud:
    gateway:
      #      default-filters:
      #        - TokenRelay
      routes:
        - id: user_client
          uri: http://localhost:8083
          predicates:
            - Path=/manager_user/**
        - id: group_client
          uri: http://localhost:8084
          predicates:
            - Path=/manager/**
        - id: report_client
          uri: http://localhost:8085
          predicates:
            - Path=/report/**


server.port: 8060
