spring:
  application:
    name: gateway
  cloud:
    gateway:
      #      default-filters:
      #        - TokenRelay
      routes:
        - id: group_client
          uri: http://localhost:8084
          predicates:
            - Path=/manager/**
#          filters:
#            - RemoveRequestHeader=Cookie
        - id: report_client
          uri: http://localhost:8085
          predicates:
            - Path=/report/**
  #          filters:
  #            - RemoveRequestHeader=Cookie


server.port: 8060
